# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Quick start: `brew install pre-commit && pre-commit install`
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: requirements-txt-fixer
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black-jupyter
    # https://pre-commit.com/#top_level-default_language_version
    language_version: python3.12
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
    -   id: mypy
