version: '3'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    command: mlflow server --host 0.0.0.0 --port 8080
    ports:
        - "8080:8080"
    volumes:
      - mlflow-data:/mlflow
    environment:
      - MLFLOW_HOME=/mlflow
volumes:
  mlflow-data:
